### ISSUE TITLE
include/exclude files

### ISSUE THREAD

**Issue by phoenixr-codes** [allay-mc/allay#14]
While this could be implemented with a script, having this built-in would be good because it is such a common thing to do which is necessary to keep unnecessary files out of the build.

```toml
# ...
[build]
include = ["**/*.json", "**/*.png"]
exclude = ["**/*.in", "**/*.txt"]
```

Setting both `include` and `exclude` however would be an error. The manifest file will remain in all cases.

This process should happen at the very end (after pre-scripts, before post-scripts).
