### ISSUE TITLE
Redesign of allay.toml

### ISSUE THREAD

**Issue by phoenixr-codes** [allay-mc/allay#25]
```toml
[project.name]
en-us = "Name"
de-de= "Name"

[project]
description = "Description"
# `name` and `description` may be a string to be applied on all
# languages
version = "1.0"
authors = ["John Doe"]
license = "MIT"
url = "http://example.org"

[localization]
primary-language = "en-us"
groups = [
  ["de-at"]
]
# `groups` overrides everything so you might copy-paste and
# edit the default table

[pack.BP]
name = { en-us = "[BP] Name" }
# similar to `localization.groups`
description = { en-us = "Desc" }

[[script]]
run = "scripts/foo.py"
with = "python"
options = {
  opt1 = "value",
  opt2 = ["multi", "value"],
}
# `options` passed as a JSON object; conflicts with `args`

[[script]]
run = "allaycheck"
post-process = true
# `post-process`: script runs after build
args = ["x=1", "x=2"]

[build]
use-custom-manifest = false
```
