### ISSUE TITLE
Override build path within CLI or config file

### ISSUE THREAD

**Issue by phoenixr-codes** [allay-mc/allay#37]
Instead of having a hard coded build path, let the user specify a path via the config file (low priority) or the CLI (high priority).

```toml
[build]
output = "path/to/build.mcaddon"
```

```console
allay build -o path/to/build.mcaddon
```
