### ISSUE TITLE
inform about manifest.json

### ISSUE THREAD

**Issue by phoenixr-codes** [allay-mc/allay#5]
A warning should be displayed when a `manifest.json` file is found in one of the pack's root directory. This warning should be able to be omitted within the configuration file which could look like this:

```toml
[build]
# ...
ignore-custom-manifest = true
```
